### ISSUE TITLE
Some issue in scripts

### ISSUE THREAD

**Issue by xma82** [ernstlab/ChromGene#7]
I found that scripts in ChromGene is not suitable for nonmodel organism, liking plants and so on. I hope that the authors can improve these scripts. 

In addition, when running the "chromgene_posteriors_to_components.py" scripts, some error happened as follows, 
"Traceback (most recent call last):
  File "./ChromGene/scripts/chromgene_posteriors_to_components_xma.py", line 146, in <module>
    main()
  File "./ChromGene/scripts/chromgene_posteriors_to_components_xma.py", line 85, in main
    component_assts = get_component_assts_from_posteriors(file_path, args.states_per_component)
  File "./ChromGene/scripts/chromgene_posteriors_to_components_xma.py", line 22, in get_component_assts_from_posteriors
    per_component_posteriors = posteriors_arr[:, :-1].reshape(len(posteriors_arr), -1, states_per_component).sum(axis=-1)
ValueError: cannot reshape array of size 1456462 into shape (104033,newaxis,3)".

Thanks for your help!

**Comment by BeyondTheProof** [comment]
> I found that scripts in ChromGene is not suitable for nonmodel organism, liking plants and so on. I hope that the authors can improve these scripts.

I'm sorry, how do you mean? The code should be agnostic of organism, and indeed does not use organism information anywhere. Are you having trouble?

Can you please provide the full length of commands you ran, and some example data so that I can reproduce the error?

**Comment by BeyondTheProof** [comment]
Cannot reproduce error
